### ISSUE TITLE
As a developer I want to write tests for the CSVDatabase and Client in order to validate the correctness of Chirp

### ISSUE THREAD

**Issue by T0rvadaL** [ITU-BDSA2024-GROUP26/Chirp#10]
User story:
In order to make sure Chirp runs correctly, We need systematic testing.

Acceptance criteria:
All tests, should be relevant and correct.
All tests combined should cover close to 100% of the code

**Comment by T0rvadaL** [comment]
Jeg tager unit tests til Client

**Comment by JojoStarman** [comment]
Jovana og jeg tager integrations test for databasen

**Comment by vbjo** [comment]
Jeg tager end to end test
