### ISSUE TITLE
As a developer I want integration and E2E-tests for Chirp.CLI.Clients interactions with the web service

### ISSUE THREAD

**Issue by torbjornjohannsen** [ITU-BDSA2024-GROUP26/Chirp#19]
Note: This should NOT access the actual production server, but rather mock it via a locally hosted instance(where we can arrange the data to be whatever we want as well)

Acceptance Criteria: 
- E2E test for *cheeping*, ie inputting a message into the client that then gets stored in the database of the service 
- E2E test for *reading*, ie asking the client to read and it properly retrieving the cheeps from the service
- Integration test for storing JSON-formatted data in the database via the web service(Should be at the detail level of mocking a HTTP-post request and and validating the database) 
- Integration test for retrieving JSON-formatted data from the database via the web service(Likewise at the detail level of mocking a HTTP-get request and validating the response)

**Comment by torbjornjohannsen** [comment]
Lacking last 2 criteria

**Comment by vbjo** [comment]
Fixed the tests in the branch chirp_cli
