### ISSUE TITLE
As a developer I want to switch the Database to a File-based SQLite Database 

### ISSUE THREAD

**Issue by jnov00** [ITU-BDSA2024-GROUP26/Chirp#29]
Acceptance Criteria:
- The application uses an SQLite database for data storage and retrieval instead of the previous CSV-based solution.
- All database interactions are encapsulated within a dedicated abstraction layer (DBFacade.cs).
- Existing functionalities continue to work with the new SQLite database.

**Comment by torbjornjohannsen** [comment]
> All database interactions are encapsulated within a dedicated abstraction layer (DBFacade.cs).

We already have a database abstraction in IDatabaseRepository. Use that and switching to using the new database in the client is effortless
